stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: wls-pipeline:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34218
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./model.yaml
  - applyYamlConfig:
      path: ./binding.yaml
timeout: 60
notification: {}
